[package]
name = "solana-escrow"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.7.8"
thiserror = "1.0.24"

[lib]
crate-type = ["cdylib", "lib"]
